/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ehongka' at '7/11/16 1:27 PM' with Gradle 2.13
 * this is a
 * ok line for sonarqube
 *
 * kjklj sdfisdfa
 * sdfsf
 * dfs
 *
 *
 * @author ehongka, @date 7/11/16 1:27 PM
 */
class Library {
    /**
     * sdfsff
     * @return true
     */
    boolean someLibraryMethod() {
        true
    }
}
