/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ehongka' at '7/11/16 1:27 PM' with Gradle 2.13
 *
 * @author ehongka, @date 7/11/16 1:27 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
